use muggle;
-- ── Planes base ──────────────────────────────────────
INSERT IGNORE INTO planes (id_plan, nombre, precio, descripcion, duracion_dias) VALUES
  (1, 'Gratis',   0.00, 'Acceso al catálogo gratuito',       0),
  (2, 'Básico',   4.99, 'Acceso a catálogo básico mensual',  30),
  (3, 'Plus',     9.99, 'Acceso extendido mensual',          30),
  (4, 'Premium', 14.99, 'Acceso completo mensual',           30),
  (5, 'Prueba 7 dias', 0.00, 'Prueba gratuita por 7 dias con beneficios similares al plan Basico', 7);

-- ── Categorías ───────────────────────────────────────
INSERT IGNORE INTO categorias (nombre, descripcion) VALUES
  ('Literatura clásica',   'Obras de la literatura universal consideradas clásicos'),
  ('Psicología',           'Libros de psicología, comportamiento y mente humana'),
  ('Desarrollo personal',  'Hábitos, crecimiento, autoestima y productividad'),
  ('Novela de misterio',   'Suspense, crimen y novela policial'),
  ('Historia y política',  'Historia, política y pensamiento social'),
  ('Inglés',               'Recursos para el aprendizaje del idioma inglés'),
  ('Salud y medicina',     'Medicina, anatomía y psicopatología'),
  ('Finanzas',             'Economía personal, inversión y mentalidad financiera');

-- Helper: obtener id_categoria por nombre
-- Los INSERTs usan subconsultas para que el seed sea portátil.

-- ── Libros cortos / literatura clásica ───────────────
INSERT IGNORE INTO libros (isbn, titulo, autor, descripcion, portada, archivo, tipo, fecha_publicado, id_categoria, id_plan_minimo, estado_publicacion) VALUES
(
  '9798276599472',
  'El Príncipe',
  'Niccolò Machiavelli',
  'Tratado político de Maquiavelo sobre el ejercicio del poder, la virtud del gobernante y la realidad de la política sin adornos morales.',
  'https://covers.openlibrary.org/b/isbn/9798276599472-M.jpg',
  NULL,
  'pdf',
  '1532-01-01',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Literatura clásica' LIMIT 1),
  1,
  'publicado'
),
(
  '9788415618713',
  'Alicia en el País de las Maravillas',
  'Lewis Carroll',
  'Las aventuras de Alicia, una niña que cae a través de un agujero de conejo hacia un mundo fantástico lleno de personajes absurdos y situaciones imposibles.',
  'https://covers.openlibrary.org/b/id/8278686-M.jpg',
  NULL,
  'pdf',
  '1865-01-01',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Literatura clásica' LIMIT 1),
  1,
  'publicado'
),
(
  '9781986286121',
  'El Arte de la Guerra',
  'Sun Tzu',
  'Texto clásico chino sobre estrategia militar, planificación, liderazgo y toma de decisiones bajo incertidumbre.',
  'https://covers.openlibrary.org/b/id/13833784-M.jpg',
  'assets/books/04_-El-arte-de-la-guerra-autor-Sun-Tzu_20260515_151520.pdf',
  'pdf',
  '0500-01-01',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Literatura clásica' LIMIT 1),
  1,
  'publicado'
),
(
  '9781507170656',
  'El Principito',
  'Antoine de Saint-Exupéry',
  'Relato poético sobre la amistad, la imaginación y la forma en que los adultos olvidan lo esencial de la vida.',
  'https://covers.openlibrary.org/b/isbn/9781507170656-M.jpg',
  'assets/books/El Principito.pdf',
  'pdf',
  '1943-04-06',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Literatura clásica' LIMIT 1),
  1,
  'publicado'
),
(
  '9788491050773',
  'Edipo Rey',
  'Sófocles',
  'Tragedia griega que explora el destino, el libre albedrío y la búsqueda de la verdad a través del rey Edipo.',
  'https://covers.openlibrary.org/b/id/12330666-M.jpg',
  NULL,
  'pdf',
  '0429-01-01',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Literatura clásica' LIMIT 1),
  1,
  'publicado'
),
(
  '9781480096134',
  'El Corazón de las Tinieblas',
  'Joseph Conrad',
  'Viaje por el río Congo que se convierte en una exploración del imperialismo, la crueldad y la oscuridad de la naturaleza humana.',
  'https://covers.openlibrary.org/b/isbn/9781480096134-M.jpg',
  NULL,
  'pdf',
  '1902-01-01',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Literatura clásica' LIMIT 1),
  1,
  'publicado'
),
(
  '9788026803423',
  'El Fantasma de Canterville',
  'Oscar Wilde',
  'Cuento irónico sobre un fantasma inglés que se encuentra con una familia americana práctica y sin temor a lo sobrenatural.',
  'https://covers.openlibrary.org/b/isbn/9788026803423-M.jpg',
  NULL,
  'pdf',
  '1887-01-01',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Literatura clásica' LIMIT 1),
  1,
  'publicado'
),
(
  '9788432290039',
  'El Túnel',
  'Ernesto Sabato',
  'Novela existencialista argentina sobre la obsesión, el aislamiento y la incomunicación de un pintor atormentado.',
  'https://covers.openlibrary.org/b/isbn/9788432290039-M.jpg',
  NULL,
  'pdf',
  '1948-01-01',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Literatura clásica' LIMIT 1),
  1,
  'publicado'
),
(
  '9781476787862',
  'El Viejo y el Mar',
  'Ernest Hemingway',
  'Novela corta sobre la lucha épica de un viejo pescador cubano con un enorme marlín en el Golfo de México.',
  'https://covers.openlibrary.org/b/isbn/9781476787862-M.jpg',
  NULL,
  'pdf',
  '1952-09-01',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Literatura clásica' LIMIT 1),
  1,
  'publicado'
),
(
  '9781535213158',
  'Esperando a Godot',
  'Samuel Beckett',
  'Obra de teatro del absurdo en la que dos personajes esperan indefinidamente a alguien que nunca llega.',
  'https://covers.openlibrary.org/b/id/12485435-M.jpg',
  NULL,
  'pdf',
  '1953-01-01',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Literatura clásica' LIMIT 1),
  1,
  'publicado'
),
(
  '9783903352513',
  'La Casa de Bernarda Alba',
  'Federico García Lorca',
  'Drama sobre la tiranía materna y la represión sexual en la España rural, símbolo de la opresión de la mujer.',
  'https://covers.openlibrary.org/b/isbn/9783903352513-M.jpg',
  NULL,
  'pdf',
  '1945-01-01',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Literatura clásica' LIMIT 1),
  1,
  'publicado'
),
(
  '9798669592257',
  'La Metamorfosis',
  'Franz Kafka',
  'Gregor Samsa despierta convertido en un insecto gigante y afronta el rechazo de su familia en una parábola sobre la alienación.',
  'https://covers.openlibrary.org/b/isbn/9798669592257-M.jpg',
  NULL,
  'pdf',
  '1915-01-01',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Literatura clásica' LIMIT 1),
  1,
  'publicado'
),
(
  '9780525504368',
  'La Perla',
  'John Steinbeck',
  'Parábola sobre la codicia y la corrupción: un pescador pobre descubre una perla enorme que destruye su vida.',
  'https://covers.openlibrary.org/b/isbn/9780525504368-M.jpg',
  NULL,
  'pdf',
  '1947-01-01',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Literatura clásica' LIMIT 1),
  1,
  'publicado'
),
(
  '9781533049711',
  'Rebelión en la Granja',
  'George Orwell',
  'Fábula política sobre animales que se rebelan contra sus dueños y reproducen la tiranía que querían derrotar.',
  'https://covers.openlibrary.org/b/isbn/9781533049711-M.jpg',
  NULL,
  'pdf',
  '1945-08-17',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Literatura clásica' LIMIT 1),
  1,
  'publicado'
),
(
  '9788494096358',
  'De la Brevedad de la Vida',
  'Lucio Anneo Séneca',
  'Ensayo estoico sobre el uso del tiempo, la sabiduría y la urgencia de vivir deliberadamente.',
  'https://covers.openlibrary.org/b/isbn/9788494096358-M.jpg',
  NULL,
  'pdf',
  '0049-01-01',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Literatura clásica' LIMIT 1),
  1,
  'publicado'
),

-- ── Libros sin PDF en el proyecto (también clásicos del fondo) ───
(
  '9780451524935',
  '1984',
  'George Orwell',
  'Novela distópica sobre una sociedad totalitaria donde el Gran Hermano vigila a cada ciudadano.',
  'https://covers.openlibrary.org/b/isbn/9780451524935-M.jpg',
  'assets/books/1984.pdf',
  'pdf',
  '1949-06-08',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Literatura clásica' LIMIT 1),
  1,
  'publicado'
),
(
  '9780060934347',
  'Don Quijote de la Mancha',
  'Miguel de Cervantes',
  'Una de las obras cumbre de la literatura universal: las aventuras del hidalgo manchego que confunde la realidad con los libros de caballería.',
  'https://covers.openlibrary.org/b/isbn/9780060934347-M.jpg',
  'assets/books/don-quijote-de-la-mancha-miguel-de-cervantes_20260515_145800.pdf',
  'pdf',
  '1605-01-16',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Literatura clásica' LIMIT 1),
  1,
  'publicado'
),
(
  '9788478884452',
  'Harry Potter y la Piedra Filosofal',
  'J. K. Rowling',
  'El primer libro de la saga Harry Potter: el joven mago descubre su herencia y comienza su educación en Hogwarts.',
  'https://covers.openlibrary.org/b/isbn/9788478884452-M.jpg',
  'assets/books/Harry_Potter_y_la_Piedra_Filosofal-J_K_Rowling_20260518_051755.pdf',
  'pdf',
  '1997-06-26',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Literatura clásica' LIMIT 1),
  2,
  'publicado'
),

-- ── Psicología ────────────────────────────────────────
(
  '9781702785891',
  'Manipulación y Psicología Oscura',
  'Alejandro Mendoza',
  'Guía sobre las técnicas de manipulación psicológica oscura, sus mecanismos y cómo protegerse de ellas.',
  'https://covers.openlibrary.org/b/id/13943764-M.jpg',
  NULL,
  'pdf',
  '2019-01-01',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Psicología' LIMIT 1),
  1,
  'publicado'
),
(
  '9781914284465',
  'Manipulación y Secretos de la Psicología Oscura',
  'Alejandro Mendoza',
  'Segunda entrega sobre manipulación, persuasión encubierta y control mental en las relaciones humanas.',
  'https://covers.openlibrary.org/b/isbn/9781914284465-M.jpg',
  NULL,
  'pdf',
  '2020-01-01',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Psicología' LIMIT 1),
  1,
  'publicado'
),
(
  '9798646039256',
  'El Arte de Manipulación y Psicología Oscura',
  'Javier Palacios',
  'Análisis de las artes oscuras de la persuasión, la manipulación y el control emocional encubierto.',
  'https://covers.openlibrary.org/b/isbn/9798646039256-M.jpg',
  NULL,
  'pdf',
  '2020-01-01',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Psicología' LIMIT 1),
  1,
  'publicado'
),
(
  '9781082568886',
  'Cómo Analizar a las Personas',
  'Robert Leary',
  'Técnicas para leer el lenguaje corporal, detectar patrones de comportamiento y entender la psicología de los demás.',
  'https://covers.openlibrary.org/b/isbn/9781082568886-M.jpg',
  NULL,
  'pdf',
  '2019-01-01',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Psicología' LIMIT 1),
  1,
  'publicado'
),
(
  '9788467028904',
  'Las 48 Leyes del Poder',
  'Robert Greene',
  'Análisis histórico de las estrategias del poder, la seducción y la influencia a través de los siglos.',
  'https://covers.openlibrary.org/b/id/14047636-M.jpg',
  NULL,
  'pdf',
  '1998-09-01',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Psicología' LIMIT 1),
  2,
  'publicado'
),
(
  '9788416029747',
  'Rompe la Barrera del No',
  'Chris Voss',
  'Técnicas de negociación del ex negociador del FBI para conseguir acuerdos en cualquier situación.',
  'https://covers.openlibrary.org/b/id/15051981-M.jpg',
  NULL,
  'pdf',
  '2016-05-17',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Psicología' LIMIT 1),
  2,
  'publicado'
),
(
  '9781947783423',
  'La Inteligencia Emocional',
  'Daniel Goleman',
  'El libro que popularizó la inteligencia emocional: cómo las emociones determinan el éxito personal y profesional.',
  'https://covers.openlibrary.org/b/id/12518522-M.jpg',
  NULL,
  'pdf',
  '1995-10-01',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Psicología' LIMIT 1),
  2,
  'publicado'
),

-- ── Desarrollo personal ───────────────────────────────
(
  '9786077477204',
  'Hábitos Atómicos',
  'James Clear',
  'Sistema probado de cómo pequeños cambios producen resultados extraordinarios mediante el poder de los hábitos.',
  'https://covers.openlibrary.org/b/isbn/9786077477204-M.jpg',
  NULL,
  'pdf',
  '2018-10-16',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Desarrollo personal' LIMIT 1),
  2,
  'publicado'
),
(
  '9788479538163',
  'El Poder de los Hábitos',
  'Charles Duhigg',
  'Por qué hacemos lo que hacemos en la vida y los negocios: la ciencia detrás de la formación y cambio de hábitos.',
  'https://covers.openlibrary.org/b/id/8250613-M.jpg',
  NULL,
  'pdf',
  '2012-02-28',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Desarrollo personal' LIMIT 1),
  2,
  'publicado'
),
(
  '9786079765453',
  'El Sutil Arte de que te Importe un Carajo',
  'Mark Manson',
  'Guía contracultural para vivir bien priorizando lo que realmente importa y dejando de perseguir una felicidad artificial.',
  'https://covers.openlibrary.org/b/isbn/9786079765453-M.jpg',
  NULL,
  'pdf',
  '2016-09-13',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Desarrollo personal' LIMIT 1),
  1,
  'publicado'
),
(
  '9788492892037',
  'Claves para una Autoestima Indestructible',
  'Elías Berntsson / Ina Arakchiyska',
  '15 claves prácticas para construir una autoestima sólida y duradera basada en el autoconocimiento.',
  'https://covers.openlibrary.org/b/id/13097183-M.jpg',
  NULL,
  'pdf',
  '2014-01-01',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Desarrollo personal' LIMIT 1),
  1,
  'publicado'
),
(
  '9788408143666',
  'El Derecho a Decir No',
  'Walter Riso',
  'Cómo establecer límites sanos y decir no sin culpa, ansias ni conflicto.',
  'https://covers.openlibrary.org/b/id/12653350-M.jpg',
  NULL,
  'pdf',
  '2012-01-01',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Desarrollo personal' LIMIT 1),
  1,
  'publicado'
),
(
  '9788498728538',
  'Emociones Tóxicas',
  'Bernardo Stamateas',
  'Cómo detectar y liberar las emociones que intoxican nuestra vida y relaciones.',
  'https://covers.openlibrary.org/b/id/13126317-M.jpg',
  NULL,
  'pdf',
  '2010-01-01',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Desarrollo personal' LIMIT 1),
  1,
  'publicado'
),
(
  '9789501524765',
  'Gente Tóxica',
  'Bernardo Stamateas',
  'Cómo identificar y neutralizar el daño de las personas que nos roban energía y bienestar.',
  'https://covers.openlibrary.org/b/id/7755011-M.jpg',
  NULL,
  'pdf',
  '2010-01-01',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Desarrollo personal' LIMIT 1),
  1,
  'publicado'
),
(
  '9788466655507',
  'Más Gente Tóxica',
  'Bernardo Stamateas',
  'Continuación de Gente Tóxica: nuevas formas de personas conflictivas y cómo relacionarnos sin sufrir.',
  'https://covers.openlibrary.org/b/id/7321790-M.jpg',
  NULL,
  'pdf',
  '2012-01-01',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Desarrollo personal' LIMIT 1),
  1,
  'publicado'
),
(
  '9788466651929',
  'Heridas Emocionales',
  'Bernardo Stamateas',
  'Cómo sanar las heridas del pasado y transformar el dolor en crecimiento personal.',
  'https://covers.openlibrary.org/b/id/13282893-M.jpg',
  NULL,
  'pdf',
  '2013-01-01',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Desarrollo personal' LIMIT 1),
  1,
  'publicado'
),
(
  '9788490705933',
  'Resultados Extraordinarios',
  'Bernardo Stamateas',
  'Claves para alcanzar el potencial máximo y obtener resultados superiores en todas las áreas de la vida.',
  'https://covers.openlibrary.org/b/id/12325851-M.jpg',
  NULL,
  'pdf',
  '2015-01-01',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Desarrollo personal' LIMIT 1),
  1,
  'publicado'
),

-- ── Novela de misterio (Ruth Rendell) ────────────────
(
  '9788401464867',
  'Dedicatoria Mortal',
  'Ruth Rendell',
  'El inspector Wexford investiga un asesinato con dedicatoria en la escena del crimen.',
  'https://covers.openlibrary.org/b/id/13656826-M.jpg',
  NULL,
  'pdf',
  '1980-01-01',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Novela de misterio' LIMIT 1),
  2,
  'publicado'
),
(
  '9788447319244',
  'Falsa Identidad',
  'Ruth Rendell',
  'Thriller psicológico sobre identidades falsas y el peligro de las apariencias.',
  'https://covers.openlibrary.org/b/isbn/9788447319244-M.jpg',
  NULL,
  'pdf',
  '1995-01-01',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Novela de misterio' LIMIT 1),
  2,
  'publicado'
),
(
  '9788401463662',
  'Un Cadáver para la Boda',
  'Ruth Rendell',
  'El inspector Wexford investiga la muerte de un invitado en una boda.',
  'https://covers.openlibrary.org/b/id/5257203-M.jpg',
  NULL,
  'pdf',
  '1967-01-01',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Novela de misterio' LIMIT 1),
  2,
  'publicado'
),
(
  '9788447319343',
  'El Juego de los Astutos',
  'Ruth Rendell',
  'Wexford frente a un caso de asesinato donde la astucia del asesino pone a prueba su experiencia.',
  'https://covers.openlibrary.org/b/isbn/9788447319343-M.jpg',
  NULL,
  'pdf',
  '1999-01-01',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Novela de misterio' LIMIT 1),
  2,
  'publicado'
),
(
  '9788484506119',
  'Un Cuento Chino',
  'Ruth Rendell',
  'Thriller de Rendell donde las historias paralelas convergen en un desenlace inesperado.',
  'https://covers.openlibrary.org/b/isbn/9788484506119-M.jpg',
  NULL,
  'pdf',
  '2003-01-01',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Novela de misterio' LIMIT 1),
  2,
  'publicado'
),
(
  '9788484506133',
  'La Crueldad de los Cuervos',
  'Ruth Rendell',
  'Historia de misterio que explora la crueldad humana y los secretos que destruyen familias.',
  'https://covers.openlibrary.org/b/id/10863367-M.jpg',
  NULL,
  'pdf',
  '2004-01-01',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Novela de misterio' LIMIT 1),
  2,
  'publicado'
),
(
  '9788420426365',
  'El Rostro Velado',
  'Ruth Rendell',
  'Wexford investiga el misterio detrás de un rostro oculto y los secretos que se esconden tras él.',
  'https://covers.openlibrary.org/b/isbn/9788420426365-M.jpg',
  NULL,
  'pdf',
  '2005-01-01',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Novela de misterio' LIMIT 1),
  2,
  'publicado'
),
(
  '9788497597524',
  'Carretera de Odios',
  'Ruth Rendell',
  'El inspector Wexford investiga casos relacionados con el tráfico en una novela de suspense y crítica social.',
  'https://covers.openlibrary.org/b/id/13984349-M.jpg',
  NULL,
  'pdf',
  '1997-01-01',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Novela de misterio' LIMIT 1),
  2,
  'publicado'
),

-- ── Historia y política ───────────────────────────────
(
  '9786079202613',
  'Por qué Fracasan los Países',
  'Daron Acemoglu / James A. Robinson',
  'Análisis de por qué algunos países prosperan y otros fracasan, centrándose en las instituciones políticas y económicas.',
  'https://covers.openlibrary.org/b/id/14572026-M.jpg',
  NULL,
  'pdf',
  '2012-03-20',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Historia y política' LIMIT 1),
  2,
  'publicado'
),
(
  '9788449320651',
  'La Promesa de la Política',
  'Hannah Arendt',
  'Ensayos sobre la filosofía política de Hannah Arendt: la acción, la libertad y el espacio público.',
  'https://covers.openlibrary.org/b/id/12338646-M.jpg',
  NULL,
  'pdf',
  '2005-01-01',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Historia y política' LIMIT 1),
  2,
  'publicado'
),
(
  '9788449342585',
  'Qué es Política',
  'Hannah Arendt',
  'Reflexiones de Arendt sobre la naturaleza de la política, el poder y la libertad humana.',
  'https://covers.openlibrary.org/b/isbn/9788449342585-M.jpg',
  NULL,
  'pdf',
  '1993-01-01',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Historia y política' LIMIT 1),
  2,
  'publicado'
),
(
  '9788494151040',
  'La Cuarta Teoría Política',
  'Aleksandr Dugin',
  'Propuesta de un marco político alternativo más allá del liberalismo, el comunismo y el fascismo.',
  'https://covers.openlibrary.org/b/isbn/9788494151040-M.jpg',
  NULL,
  'pdf',
  '2012-01-01',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Historia y política' LIMIT 1),
  3,
  'publicado'
),
(
  '9788413843322',
  'La Dictadura Infinita',
  'Luis del Pino',
  'Análisis crítico de los mecanismos del poder que perpetúan el control político en las democracias modernas.',
  'https://covers.openlibrary.org/b/id/14017994-M.jpg',
  NULL,
  'pdf',
  '2021-01-01',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Historia y política' LIMIT 1),
  2,
  'publicado'
),
(
  '9788499925585',
  'Sociedades Comparadas',
  'Jared Diamond',
  'Estudio comparativo de las sociedades humanas a lo largo de la historia para entender sus diferencias y similitudes.',
  'https://covers.openlibrary.org/b/id/14250771-M.jpg',
  NULL,
  'pdf',
  '1997-01-01',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Historia y política' LIMIT 1),
  2,
  'publicado'
),
(
  '9788433410474',
  'Los Anarquistas',
  'Cesare Lombroso',
  'Estudio criminológico clásico sobre el anarquismo y sus figuras históricas.',
  'https://covers.openlibrary.org/b/isbn/9788433410474-M.jpg',
  NULL,
  'pdf',
  '1894-01-01',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Historia y política' LIMIT 1),
  1,
  'publicado'
),
(
  '9788497341974',
  'Durruti en la Revolución',
  'Abel Paz',
  'Biografía del anarquista español Buenaventura Durruti y su papel en la Revolución Española.',
  'https://covers.openlibrary.org/b/id/13542977-M.jpg',
  NULL,
  'pdf',
  '2007-02-01',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Historia y política' LIMIT 1),
  2,
  'publicado'
),

-- ── Salud y medicina ──────────────────────────────────
(
  '9798850586317',
  'Human Anatomy for Sculptors',
  'Uldis Zarins / Sandis Kondrats',
  'Guía visual exhaustiva de anatomía humana orientada al arte, la escultura y el dibujo de la figura.',
  'https://covers.openlibrary.org/b/isbn/9798850586317-M.jpg',
  NULL,
  'pdf',
  '2023-01-01',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Salud y medicina' LIMIT 1),
  3,
  'publicado'
),
(
  '9780071466981',
  'Manual de Medicina Harrison',
  'Dennis L. Kasper / Anthony S. Fauci / et al.',
  'Manual de referencia clínica basado en los Principios de Medicina Interna de Harrison, el estándar de la medicina.',
  'https://covers.openlibrary.org/b/isbn/9780071466981-M.jpg',
  NULL,
  'pdf',
  '2005-01-01',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Salud y medicina' LIMIT 1),
  3,
  'publicado'
),

-- ── Finanzas ──────────────────────────────────────────
(
  '9781644736623',
  'Padre Rico Padre Pobre',
  'Robert T. Kiyosaki',
  'Las lecciones financieras que el padre rico enseñó a Kiyosaki sobre el dinero, los activos y la independencia económica.',
  'https://covers.openlibrary.org/b/id/13569728-M.jpg',
  NULL,
  'pdf',
  '1997-04-01',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Finanzas' LIMIT 1),
  1,
  'publicado'
),
(
  '9788413141893',
  'Pequeño Cerdo Capitalista',
  'Sofía Macías',
  'Guía práctica de finanzas personales para quienes quieren manejar bien su dinero desde cero.',
  'https://covers.openlibrary.org/b/isbn/9788413141893-M.jpg',
  NULL,
  'pdf',
  '2011-01-01',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Finanzas' LIMIT 1),
  1,
  'publicado'
),
(
  '9789681320089',
  'El Vendedor Más Grande del Mundo',
  'Og Mandino',
  'Historia motivacional sobre los secretos de la venta, el éxito y la perseverancia.',
  'https://covers.openlibrary.org/b/isbn/9789681320089-M.jpg',
  NULL,
  'pdf',
  '1968-01-01',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Finanzas' LIMIT 1),
  1,
  'publicado'
),
(
  '9798484730667',
  'Independízate de Papá Estado',
  'Carlos Galán',
  'Guía para la independencia financiera, la inversión y liberarse de la dependencia del sistema.',
  'https://covers.openlibrary.org/b/isbn/9798484730667-M.jpg',
  NULL,
  'pdf',
  '2021-01-01',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Finanzas' LIMIT 1),
  2,
  'publicado'
),
(
  '9781644730096',
  'Cómo Ganar Amigos e Influir Sobre las Personas',
  'Dale Carnegie',
  'El clásico de las habilidades sociales: principios para comunicarse mejor, ganar amigos y liderar con éxito.',
  'https://covers.openlibrary.org/b/isbn/9781644730096-M.jpg',
  NULL,
  'pdf',
  '1936-10-01',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Finanzas' LIMIT 1),
  1,
  'publicado'
),
(
  '9781455525447',
  'Las 15 Leyes Indispensables del Crecimiento',
  'John C. Maxwell',
  'Los principios de liderazgo y crecimiento personal que todo profesional debe aplicar para alcanzar su potencial.',
  'https://covers.openlibrary.org/b/id/7674852-M.jpg',
  NULL,
  'pdf',
  '2012-10-02',
  (SELECT id_categoria FROM categorias WHERE nombre = 'Finanzas' LIMIT 1),
  2,
  'publicado'
);
